site_name: Deferred & Multi-Pass Rendering
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Blog: index.md